Add option to pass additional EasyMDE options
torchbox/wagtail-markdown pull request #104
Opened 2022-07-26 09:01 UTC by frcroth

Concerning #64.

This is a very simple approach. You just define the easyMDE object in a static js file that is loaded in your backend and can supply options there.

file: project/static/js/admin/easymde_custom.js
```js
globalThis.additionalEasyMDEOptions = {
    spellChecker: false
}
```

This file just needs to be added to `wagtail_hooks.py`:
```
@hooks.register("insert_global_admin_js", order=100)
def global_admin_js():
    """Add /static/js/admin/easymde_custom.js to the admin."""
    return format_html(
        '<script src="{}"></script>',
        static("/js/admin/easymde_custom.js")
    )
```

2022-07-26 11:28 UTC, zerolab requested changes
Thank you for this @frcroth.

While it doesn't allow customisation per field which some may prefer, it is a simpler solution.

Would be great to use a proper namespace, rather than `globalThis`, and best to attach to `window`.

And add some documentation too

2022-07-26 13:21 UTC, frcroth commented
> Thank you for this @frcroth.
> 
> While it doesn't allow customisation per field which some may prefer, it is a simpler solution.
> 
> Would be great to use a proper namespace, rather than `globalThis`, and best to attach to `window`.
> 
> And add some documentation too

I'm glad that you think it is an appropriate solution. I would be happy to implement your change requests. What do you mean with a proper namespace? Do you have something specific in mind that goes beyond changing `globalThis` to `window`, like specific variable naming?
Also, by docs do you mean the README?

2022-07-26 14:21 UTC, zerolab commented
>  What do you mean with a proper namespace? Do you have something specific in mind that goes beyond changing `globalThis` to window, like specific variable naming?

I was thinking something along the lines. `window.wagtailmarkdown`. `globalThis` is ... esoteric.

>  Also, by docs do you mean the README?
Sorry, yes. All dev docs are currently in the README

2022-08-11 14:17 UTC, frcroth commented
@zerolab Are the changes fine?

2022-08-29 13:38 UTC, jeriox commented
@zerolab could you maybe take another look at this? :) would be highly appreciated

2022-08-29 20:46 UTC, zerolab commented
Hey both, I should have some time towards the end of the week so I will have a look

2022-09-16 10:56 UTC, jeriox commented
@zerolab did you find the time to have a look?

2022-09-16 11:19 UTC, zerolab commented
uh-oh, this slipped under my radar. Will have a look tonight

2022-09-17 16:14 UTC, zerolab commented
Tidied up and merged in 68aa3ef1455891555aecd4401164a3e7b4a5099c. Thank you @frcroth!

2022-09-17 16:14 UTC, closed without merging